const SHOW_RIGHT_PANEL = 'SHOW_RIGHT_PANEL';
const HIDE_RIGHT_PANEL = 'HIDE_RIGHT_PANEL';
const EXPAND_LEFT_PANEL = 'EXPAND_LEFT_PANEL';
const COLLAPSE_LEFT_PANEL = 'COLLAPSE_LEFT_PANEL';
const TOGGLE_LEFT_PANEL = 'TOGGLE_LEFT_PANEL';

const SET_MIDDLE_ROUTE = 'SET_MIDDLE_ROUTE';

const SET_CURRENT_WIDGET = 'SET_CURRENT_WIDGET';

export {
  SHOW_RIGHT_PANEL,
  HIDE_RIGHT_PANEL,
  EXPAND_LEFT_PANEL,
  COLLAPSE_LEFT_PANEL,
  TOGGLE_LEFT_PANEL,
  SET_MIDDLE_ROUTE,
  SET_CURRENT_WIDGET
};